### ISSUE TITLE
Sending to Android Wear

### ISSUE THREAD

**Issue by TechLogic** [mirsmartgrp/backend#1]
Implement sending data to Android Wear

**Comment by ghost** [comment]
04-21 12:35:52.492      423-457/? I/DASH - sensors_fifo﹕ sensors_fifo_put_event_locked: fifo full, discarding oldest event
04-21 12:35:52.492      423-457/? I/DASH - sensors_fifo﹕ sensors_fifo_put_event_locked: fifo full, discarding oldest event
04-21 12:35:52.492      423-457/? I/DASH - sensors_fifo﹕ sensors_fifo_put_event_locked: fifo full, discarding oldest event
04-21 12:35:52.492      423-457/? I/DASH - sensors_fifo﹕ sensors_fifo_put_event_locked: fifo full, discarding oldest event
04-21 12:35:52.492      423-457/? I/DASH - sensors_fifo﹕ sensors_fifo_put_event_locked: fifo full, discarding oldest event
04-21 12:35:52.492      423-457/? I/DASH - sensors_fifo﹕ sensors_fifo_put_event_locked: fifo full, discarding oldest event
04-21 12:35:52.492      423-457/? I/DASH - sensors_fifo﹕ sensors_fifo_put_event_locked: fifo full, discarding oldest event
04-21 12:35:52.492      423-457/? I/DASH - sensors_fifo﹕ sensors_fifo_put_event_locked: fifo full, discarding oldest event
04-21 12:35:52.492      423-457/? I/DASH - sensors_fifo﹕ sensors_fifo_put_event_locked: fifo full, discarding oldest event
04-21 12:35:52.492      423-457/? I/DASH - sensors_fifo﹕ sensors_fifo_put_event_locked: fifo full, discarding oldest event
04-21 12:35:52.492      423-457/? I/DASH - sensors_fifo﹕ sensors_fifo_put_event_locked: fifo full, discarding oldest event
04-21 12:35:52.492      423-457/? I/DASH - sensors_fifo﹕ sensors_fifo_put_event_locked: fifo full, discarding oldest event
04-21 12:35:52.493      423-457/? I/DASH - sensors_fifo﹕ sensors_fifo_put_event_locked: fifo full, discarding oldest event
04-21 12:35:52.493      423-457/? I/DASH - sensors_fifo﹕ sensors_fifo_put_event_locked: fifo full, discarding oldest event
04-21 12:35:52.493      423-457/? I/DASH - sensors_fifo﹕ sensors_fifo_put_event_locked: fifo full, discarding oldest event
04-21 12:35:52.493      423-457/? I/DASH - sensors_fifo﹕ sensors_fifo_put_event_locked: fifo full, discarding oldest event
04-21 12:35:52.493      423-457/? I/DASH - sensors_fifo﹕ sensors_fifo_put_event_locked: fifo full, discarding oldest event
04-21 12:35:52.493      423-457/? I/DASH - sensors_fifo﹕ sensors_fifo_put_event_locked: fifo full, discarding oldest even
